# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e9abccc6b12496a18a0133af07081a66763cba57a109073314f739381169b5032ac5731943d96e71293973c35eabd65ee31f1bc5d5212908ce64d8b57741eca

test:
  secret_key_base: b782f2fafc65eb1d6f07df170470a497f40ba1665abccfee3178f7cdcd7a2fe77dc4fabdf6a503599b4bd18e423a1c35b55e7c5dd2d758ba2076ce00ff7ab200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
